---
    - name: Provision Web Servers
      hosts: static 
      tasks:
    
        - name: Install pip3
          apt:
            update_cache: yes
            name: python3-pip
          become: yes
    
        - name: Install python docker sdk
          shell: |
            pip3 install docker
          become: yes
    
        - name: Install docker
          apt:
            name: docker.io
          become: yes
    
        - name: Start Docker
          shell: |
            systemctl start docker
            systemctl enable docker
          become: yes

        - name: Run Image
          shell: docker run --name hello -dit -p 80:80 -p 443:443 jrchacon89135/ec2-nginx-static
          become: yes
